[chore] rewritting depenencies with `uv`, add configuration for reranker benchmark
Marker-Inc-Korea/AutoRAG-example-korean-embedding-benchmark pull request #6
Opened 2024-12-14 19:10 UTC by sigridjineth

## Changes
1. Added `uv` as a project management tool to provide better organization and long-term maintainability.
2. Implemented configurable options for evaluating rerankers, maintaining the existing OpenAI embedding model support and simultaneously enabling comprehensive cross-encoder configurations with trust_remote_code capabilities.

2024-12-14 19:22 UTC, sigridjineth commented
cc. @vkehfdl1

2024-12-16 07:41 UTC, vkehfdl1 requested changes
Why don't we use uv at the AutoRAG main repo also?

2024-12-16 07:41 UTC, vkehfdl1 commented on .gitignore
> +.python_version
Please add new line

2024-12-16 07:41 UTC, vkehfdl1 commented on pyproject.toml
> +requires-python = ">=3.11"
We need more than python 3.10

2024-12-16 07:41 UTC, vkehfdl1 commented on config/embedding_benchmark.yaml
> +           - gte-multilingual-reranker-base
Do not change this since this is embedding benchmark repository

2024-12-16 08:54 UTC, realsigridjin commented on config/embedding_benchmark.yaml
> +           - gte-multilingual-reranker-base
@vkehfdl1 clearly mistake. gotcha

2024-12-30 08:58 UTC, closed without merging